-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Employees Table
create table public.employees (
  id uuid references auth.users not null primary key,
  email text unique not null,
  full_name text,
  department text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Activity Logs Table (High frequency)
create table public.activity_logs (
  id bigint generated by default as identity primary key,
  employee_id uuid references public.employees(id) not null,
  window_title text,
  app_name text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  duration_seconds integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Daily Summaries Table (Aggregated)
create table public.daily_summaries (
  id bigint generated by default as identity primary key,
  employee_id uuid references public.employees(id) not null,
  date date not null,
  total_active_seconds integer default 0,
  top_apps jsonb default '[]'::jsonb, -- Array of {app_name, duration}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(employee_id, date)
);

-- Row Level Security (RLS)

-- Employees: Admins can view all, Users can view themselves
alter table public.employees enable row level security;

create policy "Admins can view all employees"
  on public.employees for select
  using (auth.role() = 'service_role'); -- Assuming admin uses service role or specific admin flag

create policy "Employees can view own profile"
  on public.employees for select
  using (auth.uid() = id);

-- Activity Logs: Agents (Users) insert their own, Admins view all
alter table public.activity_logs enable row level security;

create policy "Employees can insert own logs"
  on public.activity_logs for insert
  with check (auth.uid() = employee_id);

create policy "Admins can view all logs"
  on public.activity_logs for select
  using (auth.role() = 'service_role');

-- Daily Summaries: Admins view all
alter table public.daily_summaries enable row level security;

create policy "Admins can view all summaries"
  on public.daily_summaries for select
  using (auth.role() = 'service_role');
